### PR TITLE
fix(logging): adjust filebeat log parse config

### PR DESCRIPTION
**Pull request by kvhswong**
I removed the filebeat configuration for pulling from an application specific log file and left the one writing to stdout. Not sure if there is a need to write to an application specific log file but I can adjust if necessary.

Below is a sample of the taxbracket log. I had to adjust the filebeats configuration to account for a 4 digit year instead of just 2.

```
2016/08/22 23:26:56 Tax cost for [income=120000] and [filingStatus=single] is [tax=26636.75] using the following tax bracket for calculations: {91151 190150 28 15 18558.75}
2016/08/22 23:26:56 GET	/taxbracket/2016/single?income=120000	TaxCalc	78.861µs
2016/08/22 23:28:26 GET	/taxbrackets/2016	AnnualTaxBrackets	1.390003ms
2016/08/22 23:28:32 GET	/taxbrackets/2016	AnnualTaxBrackets	106.244µs
```

### CODE REVIEW

**Comment by gregdurham** [comment]
This looks like it should be good. How are you handling error logs vs standard out logs? Do they both just get sent to stdout? How do we know the log level (INFO, DEBUG, etc) Do we have a way of tracing these? i.e. x calls this service, can we reference that call to this service back to a specific request? I.e. can we get a session id, or something to link this all the way through so we know/can troubleshoot what is failing, and specifically in which context it is failing

**Comment by kvhswong** [comment]
Go's standard logging library does not provide the ability to set levels on the logs. I would have to Include this as part of the log statement itself. There are libraries out there that support this, which would take some investigation.

I would have to see how Go handles exceptions. From some of the tests that I have run, I didn't see a stack trace, just the error message. Need to look into that further.

As for contextual information, since this is just a basic HTTP service with no authentication, there really is no contextual information. The caller would have to examine itself error logs as to why the request failed. For example, look at the http status code, error response, etc.

For now, I need to implement the service in core to call this service and we can revisit these topics after I complete that. All good questions, I promise I won't forget.

**Comment by gregdurham** [comment]
Oh, believe me it gives a stack trace :)

**Comment by gregdurham** [comment]
Here is the logger I have been using: https://github.com/Sirupsen/logrus

**Comment by kvhswong** [comment]
OK, I'll create a Jira somewhere to track using better logger as well as plugging in gometric.

**Comment by gregdurham** [comment]
sounds good.

**Comment by kvhswong** [comment]
Can I merge this then?

**Comment by bondricek** [comment]
👍

**Comment by kvhswong** [comment]
Thanks Brad, going to wait for the Olen to merge the nomad file so I can test the CD process. Will merge this once Olen's PR is merged.

**Comment by kvhswong** [comment]
Olen's [PR](https://github.com/trizic/trizic-ops/pull/436) got merged. Merging now.

**Pull request merged**
